language: node_js
node_js:
  - "node"
  - "6.11.2"

script:
  - npm test

after_script:
  - npm run coverage

env:
  global:
    - RANDOM_TOKEN=Randomtoken

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE postit_test;' -U postgres